# Generated by Django 5.1.6 on 2025-03-21 11:46

import django.db.models.deletion
import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('developer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('monthly_rate', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('planned_start_date', models.DateTimeField(blank=True, null=True)),
                ('planned_end_date', models.DateTimeField(blank=True, null=True)),
                ('developers', models.ManyToManyField(blank=True, null=True, related_name='projects', to='task.developer')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=task.models.project_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='task.projectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On-Hold', 'On-Hold'), ('Blocked', 'Blocked')], default='To Do', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('planned_start_date', models.DateTimeField(blank=True, null=True)),
                ('planned_end_date', models.DateTimeField(blank=True, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.projectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='EnhancementHistory',
            fields=[
                ('enhancement_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('enhancement_description', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('developer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.developer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.projectdetail')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
            options={
                'db_table': 'enhancement_history',
            },
        ),
        migrations.CreateModel(
            name='BugHistory',
            fields=[
                ('bug_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('bug_description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.developer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.projectdetail')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
            options={
                'db_table': 'bug_history',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.projectdetail')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
