# Generated by Django 5.1.6 on 2025-03-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='developers',
            field=models.ManyToManyField(related_name='projects', to='task.developer'),
        ),
    ]
