# Generated by Django 5.1.6 on 2025-03-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_projectdetail_developers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='developers',
        ),
        migrations.CreateModel(
            name='BugHistory',
            fields=[
                ('bug_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('bug_description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.projectdetail')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.developer')),
            ],
            options={
                'db_table': 'bug_history',
            },
        ),
        migrations.CreateModel(
            name='EnhancementHistory',
            fields=[
                ('enhancement_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('enhancement_description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.projectdetail')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.developer')),
            ],
            options={
                'db_table': 'enhancement_history',
            },
        ),
    ]
