# Generated by Django 5.1.6 on 2025-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_image_project_developer_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='project',
        ),
        migrations.AlterField(
            model_name='developer',
            name='password_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enhancementhistory',
            name='enhancement_description',
            field=models.TextField(null=True),
        ),
    ]
