# Generated by Django 5.1.6 on 2025-03-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_developer_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='developers',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='task.developer'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='planned_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='planned_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
