# Generated by Django 5.1.6 on 2025-03-20 18:42

import django.db.models.deletion
import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_projectdetail_developers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bughistory',
            old_name='updated_by',
            new_name='developer_id',
        ),
        migrations.RemoveField(
            model_name='enhancementhistory',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='enhancementhistory',
            name='developer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.developer'),
        ),
        migrations.AlterField(
            model_name='enhancementhistory',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to=task.models.project_file_path),
        ),
    ]
