# Generated by Django 5.1.6 on 2025-03-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_rename_updated_by_bughistory_developer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bughistory',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
